#pragma once

#define IDR_SHELLFOLDER 1004
#define IDR_EXTENSION 1009
#define IDI_BACKUP 101

#define IDD_PASSWORD 200
#define IDC_PASSWORD_PROMPT 201
#define IDC_PASSWORD_EDIT 202
#define IDC_PASSWORD_ERROR 203

#define IDS_SHELLEXT_NAME 300
#define IDS_SHELLEXT_SIZE 302
#define IDS_SHELLEXT_ERROR_CAPTION 303
#define IDS_SHELLFOLDER_DELETE 360
#define IDS_SHELLFOLDER_MULTIPLE_DELETE 361
#define IDS_SHELLFOLDER_FILE_DELETE_CAPTION 362
#define IDS_SHELLFOLDER_FILES_DELETE_CAPTION 363
#define IDS_SHELLFOLDER_TYPE 364
#define IDS_SHELLFOLDER_CANNOT_PERFORM 366
#define IDS_SHELLFOLDER_DFM_HELP_OPEN 367

// Password dialog (runtime-localized; English also in STRINGTABLE as fallback).
#define IDS_PASSWORD_CAPTION 400
#define IDS_PASSWORD_PROMPT 401
#define IDS_PASSWORD_INCORRECT 402
#define IDS_PASSWORD_OK 403
#define IDS_PASSWORD_CANCEL 404

// Browse / open error messages.
#define IDS_ERR_ARCHIVE_ENCRYPTED 410
#define IDS_ERR_INVALID_PASSWORD 411
#define IDS_ERR_PASSWORD_CANCELLED 412
#define IDS_ERR_PARENT_MISSING 413
#define IDS_ERR_UNSUPPORTED_VERSION 414
#define IDS_ERR_UNABLE_OPEN 415
#define IDS_ERR_NO_VOLUMES 416
#define IDS_ERR_PATH_EMPTY 417
#define IDS_ERR_NTFS_PARSE 418
#define IDS_ERR_NTFS_ONLY 419
#define IDS_DISK_FORMAT 420
#define IDS_VOLUME_FORMAT 421
#define IDS_TIP_ARCHIVE_FOLDER 422
#define IDS_TIP_ARCHIVE_FILE 423
#define IDS_TIP_SIZE 424
#define IDS_TIP_SOURCE 425
#define IDS_COLUMN_DATE_MODIFIED 426
#define IDS_COLUMN_TYPE 427
#define IDS_OPEN_ITEM_FAILED 428
#define IDS_TYPE_DISK 429
#define IDS_TYPE_VOLUME 430
#define IDS_TYPE_FILE_FOLDER 431
#define IDS_TYPE_FILE 432
#define IDS_PASSWORD_CAPTION_DEFAULT 433
#define IDS_ERR_FILE_TOO_LARGE 434
